### PR TITLE
maximus: Fix 'Segmentation fault'

### PR DESCRIPTION
**Pull request by sc0w**
Fixes https://github.com/mate-desktop/mate-netbook/issues/46

### CODE REVIEW

**Comment by sc0w** [comment]
@flexiondotorg I did little changes, I think now the fix is better, ready to merge.

**Comment by flexiondotorg** [comment]
Thanks @sc0w, I will test it again.

**Comment by monsta** [comment]
Oh, so it happened because `gdk_display_get_default` was called before `gtk_init`...?

**Comment by flexiondotorg** [comment]
Rebuilt and tested. Confirmed fixed. Thanks @sc0w :+1:

**Pull request merged**
