### PR TITLE
window picker: add minimize button

### PR DESCRIPTION
**Pull request by sub77**
[feature-request #36](https://github.com/mate-desktop/mate-netbook/issues/36)

### CODE REVIEW

**Comment by raveit65** [comment]
Sorry, i can't test/review because i don't use this package for fedora.
But it seems to look fine with a quick overview.

**Comment by sc0w** [comment]
@sub77 please, can you rebase this PR against master to see the travis checks?

**Comment by milouse** [comment]
This PR introduces two icons (close and minify buttons images) and stores them out of the user current theme. I presume this is because most standard theme does not embed a `window-minified` icon.

I would like to discuss that. Maybe a proper way to implement this feature would be to first try to retrieve the icon from the them and only if there is no icon with that name use the svg included in this PR. Thus we should add a `window-minify` icon in the Mate default icon themes to be sure this PR will match user chose theme, at least for all the default ones.

What do you think?

**Comment by sc0w** [comment]
@milouse  yes, new PR is welcome :)

**Comment by raveit65** [comment]
I guess this can be closed.

**Pull request closed without merging**
