### PR TITLE
window picker applet: don't mess with maximus settings

### PR DESCRIPTION
**Pull request by monsta**

### CODE REVIEW

**Comment by stefano-k** [comment]
I added this code in the past because there were a lot of users complaining.
Can I ask why do you want to remove this? :)

**Comment by monsta** [comment]
Because I don't want it to unconditionally change maximus settings that I've set up before.

Also yesterday @flexiondotorg tried to figure out why all the windows have weird behavior when window picker applet is on the panel. I'm sure he can tell you why the applet shouldn't mess with the settings that don't belong to it. :)

**Comment by flexiondotorg** [comment]
@stefano-k There are gschema settings for controlling Maximus behaviour. If I configure them a particular way I don't want the reverted each time the Window Picker applet is started. I've added configuration options for Maximus to MATE Tweak, so this give users easy access to these settings.

**Comment by stefano-k** [comment]
Released as 1.9.91 for testing

**Pull request closed without merging**
